/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hockeyteams;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author Darian
 */
public class AddPlayerDialog extends javax.swing.JDialog {

    private HockeyPlayer player;
    private List<String> nicknames;
    
    //Moved all the control declarations up here so I could edit 2 of them
    private javax.swing.JButton confirmButton;
    private javax.swing.JPanel entryPanel;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField gradeField;
    private javax.swing.JLabel gradeLabel;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JButton nicknamesButton;
    private javax.swing.JTextField number1Field;
    private javax.swing.JTextField number2Field;
    private javax.swing.JTextField number3Field;
    private javax.swing.JLabel numbersLabel;
    private javax.swing.JComboBox<Position> positionComboBox;//These combo boxes are usually strings
    private javax.swing.JLabel positionLabel;
    private javax.swing.JComboBox<Team> teamComboBox;//I needed to change the type
    private javax.swing.JLabel teamLabel;
    
    /**
     * Creates new form AddPlayerDialog
     */
    public AddPlayerDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        nicknames = new ArrayList<>();//Initialise nicknames list
    }
    
    /**
     * Show this dialog
     * @return Player as entered in this dialog
     */
    public HockeyPlayer showDialog(){
        setVisible(true);//Show the dialog and wait for it to close
        return player;//Return the player that will be setup before closing
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        entryPanel = new javax.swing.JPanel();
        lastNameLabel = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        firstNameLabel = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        teamLabel = new javax.swing.JLabel();
        teamComboBox = new javax.swing.JComboBox<>();
        gradeLabel = new javax.swing.JLabel();
        gradeField = new javax.swing.JTextField();
        positionLabel = new javax.swing.JLabel();
        positionComboBox = new javax.swing.JComboBox<>();
        numbersLabel = new javax.swing.JLabel();
        number1Field = new javax.swing.JTextField();
        number2Field = new javax.swing.JTextField();
        number3Field = new javax.swing.JTextField();
        nicknamesButton = new javax.swing.JButton();
        confirmButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 100};
        entryPanel.setLayout(jPanel1Layout);

        lastNameLabel.setText("Last Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        entryPanel.add(lastNameLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        entryPanel.add(lastNameField, gridBagConstraints);

        firstNameLabel.setText("First Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        entryPanel.add(firstNameLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        entryPanel.add(firstNameField, gridBagConstraints);

        teamLabel.setText("Team");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        entryPanel.add(teamLabel, gridBagConstraints);

        teamComboBox.setModel(new DefaultComboBoxModel<Team>(Team.values()));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        entryPanel.add(teamComboBox, gridBagConstraints);

        gradeLabel.setText("Grade");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        entryPanel.add(gradeLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        entryPanel.add(gradeField, gridBagConstraints);

        positionLabel.setText("Position");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        entryPanel.add(positionLabel, gridBagConstraints);

        positionComboBox.setModel(new DefaultComboBoxModel<Position>(Position.values()));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        entryPanel.add(positionComboBox, gridBagConstraints);

        numbersLabel.setText("Number Preferences");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridheight = 3;
        entryPanel.add(numbersLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        entryPanel.add(number1Field, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        entryPanel.add(number2Field, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        entryPanel.add(number3Field, gridBagConstraints);

        nicknamesButton.setText("Nicknames");
        nicknamesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicknamesButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = 2;
        entryPanel.add(nicknamesButton, gridBagConstraints);

        getContentPane().add(entryPanel, java.awt.BorderLayout.CENTER);

        confirmButton.setText("Add");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        getContentPane().add(confirmButton, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        //Declaring variables
        String lastName, firstName;
        int grade;
        Team team;
        Position position;
        int[] numbers = new int[3];//Empty int array of length 3. It will always be 3 long
        
        //Name is easy, just get text from fields
        lastName = lastNameField.getText();
        firstName = firstNameField.getText();
        
        //Team and position just require casting
        team = (Team)teamComboBox.getSelectedItem();//We know the type is right because of the editing of the declaration
        position = (Position)positionComboBox.getSelectedItem();
        
        //The trick bit where things can go wrong
        try{
            grade = Integer.parseInt(gradeField.getText());//Try to parse the input
            
            //Try to parse numbers from numbers fields
            numbers[0] = Integer.parseInt(number1Field.getText());
            numbers[1] = Integer.parseInt(number2Field.getText());
            numbers[2] = Integer.parseInt(number3Field.getText());
            
            //Create the player
            player = new HockeyPlayer(lastName, firstName, team, grade, position, numbers);
            
            //Set nicknames
            player.setNicknames(nicknames);
            
            //Close the window (and thus return the value)
            setVisible(false);
            dispose();
            
        }catch(Exception e){//Catch any possible problems
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void nicknamesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicknamesButtonActionPerformed
        //Use StringListEditorDialog to get string list
        nicknames = new StringListEditorDialog(new JFrame(), nicknames).showDialog();
    }//GEN-LAST:event_nicknamesButtonActionPerformed
/** This sneakily comments out all the declarations so we can move them
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmButton;
    private javax.swing.JPanel entryPanel;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField gradeField;
    private javax.swing.JLabel gradeLabel;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JButton nicknamesButton;
    private javax.swing.JTextField number1Field;
    private javax.swing.JTextField number2Field;
    private javax.swing.JTextField number3Field;
    private javax.swing.JLabel numbersLabel;
    private javax.swing.JComboBox<String> positionComboBox;
    private javax.swing.JLabel positionLabel;
    private javax.swing.JComboBox<String> teamComboBox;
    private javax.swing.JLabel teamLabel;
    // End of variables declaration//GEN-END:variables
*/
}
