/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hockeyteams;

import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.JSpinner;

/**
 *
 * @author John
 */
public class IntArrayEditorDialog extends javax.swing.JDialog {

    GridLayout layout;
    List<JSpinner> spinners;
    
    int[] array;
    
    /**
     * Creates new form IntArrayEditorDialog
     */
    public IntArrayEditorDialog(java.awt.Frame parent, int[] value) {
        super(parent, true);
        initComponents();
        
        spinners = new ArrayList<>();//Init arrayList
        layout = (GridLayout)spinnerPanel.getLayout();//Get panel layout
        layout.setColumns(0);
        
        spinnerPanel.removeAll();//Remove spinners from panel
        for(int number : value){//For each number
            JSpinner spinner = new JSpinner();//Create new spinner
            spinner.setValue(number);//Set spinner value
            spinners.add(spinner);//Add spinner to list
            spinnerPanel.add(spinner);//Add spinner to panel
        }
        layout.setRows(spinners.size());//Set row count for each spinner
        spinnerPanel.setSize(100, spinners.size() * 40);//Set size of panel tall enough for spinners
    }
    
    public int[] showDialog(){
        setSize(100, (spinners.size() * 50) + 100);//Set windows size (includeds title bar bc Windows, man, how does that work?)
        setVisible(true);
        return array;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spinnerPanel = new javax.swing.JPanel();
        confirmButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        spinnerPanel.setLayout(new java.awt.GridLayout());
        getContentPane().add(spinnerPanel, java.awt.BorderLayout.CENTER);

        confirmButton.setText("Ok");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        getContentPane().add(confirmButton, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        array = new int[spinners.size()];//create array
        for(int i = 0; i < spinners.size(); i++){//For each spinner
            array[i] = (int)spinners.get(i).getValue();//Put spinner value in array
        }
        setVisible(false);//Close dialog
        dispose();
    }//GEN-LAST:event_confirmButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmButton;
    private javax.swing.JPanel spinnerPanel;
    // End of variables declaration//GEN-END:variables
}
