/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hockeyteams;

import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JSpinner;
import javax.swing.JTextField;

/**
 *
 * @author John
 */
public class StringListEditorDialog extends javax.swing.JDialog {

    GridLayout layout;
    List<JTextField> fields;
    
    List<String> list;
    
    /**
     * Creates new form IntArrayEditorDialog
     */
    public StringListEditorDialog(java.awt.Frame parent, List<String> value) {
        super(parent, true);
        initComponents();
        
        fields = new ArrayList<>();//Init arrayList
        layout = (GridLayout)fieldPanel.getLayout();//Get panel layout
        layout.setColumns(1);
        
        fieldPanel.removeAll();//Remove fields from panel
        for(String string : value){//For each number
            JTextField field = new JTextField();//Create new field
            field.setText(string);//Set field value
            fields.add(field);//Add field to list
            fieldPanel.add(field);//Add field to panel
        }
        layout.setRows(fields.size());//Set row count for each field
        fieldPanel.setSize(100, fields.size() * 40);//Set size of panel tall enough for fields
    }
    
    public List<String> showDialog(){
        setSize(100, (fields.size() * 50) + 100);//Set windows size (includeds title bar bc Windows, man, how does that work?)
        setVisible(true);
        return list;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        fieldPanel = new javax.swing.JPanel();
        buttonsPanel = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        confirmButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        fieldPanel.setLayout(new java.awt.GridLayout());
        getContentPane().add(fieldPanel, java.awt.BorderLayout.CENTER);

        buttonsPanel.setLayout(new java.awt.GridBagLayout());

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        buttonsPanel.add(addButton, gridBagConstraints);

        confirmButton.setText("Ok");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(confirmButton, new java.awt.GridBagConstraints());

        getContentPane().add(buttonsPanel, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        if(list == null){
            list = new ArrayList<>();
        }
        for(JTextField field : fields){
            list.add(field.getText());
        }
        setVisible(false);
        dispose();
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        JTextField field = new JTextField();//Create new field
        field.setText("");//Set field value
        fields.add(field);//Add field to list
        fieldPanel.add(field);//Add field to panel
        invalidate();//Repaint
        validate();
        repaint();
    }//GEN-LAST:event_addButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton confirmButton;
    private javax.swing.JPanel fieldPanel;
    // End of variables declaration//GEN-END:variables
}
