/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package matchinggameswaine;

import javax.swing.ImageIcon;
import java.util.*;
/**
 *
 * @author jonswaine
 */
public class matchingGameSwaineUI extends javax.swing.JFrame {
    
    //Stores value of cards
    ArrayList<String> cards = new ArrayList();
    //Stores card set (two of ever type of card)
    ArrayList<String> set = new ArrayList();
    
    //Setting images for cards
    ImageIcon a = new ImageIcon(getClass().getResource("/matchinggameswaine/ram.jpg")); // NOI18N
    ImageIcon b = new ImageIcon(getClass().getResource("/matchinggameswaine/case.jpg"));
    ImageIcon c = new ImageIcon(getClass().getResource("/matchinggameswaine/dvd.jpg"));
    ImageIcon d = new ImageIcon(getClass().getResource("/matchinggameswaine/harddrive.jpg"));
    ImageIcon e = new ImageIcon(getClass().getResource("/matchinggameswaine/keyboard.jpg"));
    ImageIcon f = new ImageIcon(getClass().getResource("/matchinggameswaine/mice.jpg"));
    ImageIcon g = new ImageIcon(getClass().getResource("/matchinggameswaine/monitor.jpg"));
    ImageIcon h = new ImageIcon(getClass().getResource("/matchinggameswaine/printer.jpg"));
    ImageIcon back = new ImageIcon(getClass().getResource("/matchinggameswaine/cardback.jpg"));
    ImageIcon done = new ImageIcon(getClass().getResource("/matchinggameswaine/done.jpg"));
    //Count: How many cards are flipped
    //c1, c2 first and second card flipped
    //card1 and card2 are unused
    int count, c1, c2, card1, card2;
    int cardsLeft = 16;
    //Stores card states (0=flipped, 1=normal, 2=done)
    int[] change = new int[16];
    
    /**
     * Creates new form matchingGameSwaineUI
     */
    public matchingGameSwaineUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCard1 = new javax.swing.JButton();
        btnCard2 = new javax.swing.JButton();
        btnCard3 = new javax.swing.JButton();
        btnCard4 = new javax.swing.JButton();
        btnCard6 = new javax.swing.JButton();
        btnCard5 = new javax.swing.JButton();
        btnCard8 = new javax.swing.JButton();
        btnCard7 = new javax.swing.JButton();
        btnCard10 = new javax.swing.JButton();
        btnCard9 = new javax.swing.JButton();
        btnCard12 = new javax.swing.JButton();
        btnCard11 = new javax.swing.JButton();
        btnCard14 = new javax.swing.JButton();
        btnCard13 = new javax.swing.JButton();
        btnCard16 = new javax.swing.JButton();
        btnCard15 = new javax.swing.JButton();
        btnPlay = new javax.swing.JButton();
        btnGuessAgain = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Big Caslon", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Matching Game");

        btnCard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchinggameswaine/cardback.jpg"))); // NOI18N
        btnCard1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard1ActionPerformed(evt);
            }
        });

        btnCard2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchinggameswaine/cardback.jpg"))); // NOI18N
        btnCard2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard2ActionPerformed(evt);
            }
        });

        btnCard3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchinggameswaine/cardback.jpg"))); // NOI18N
        btnCard3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard3ActionPerformed(evt);
            }
        });

        btnCard4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchinggameswaine/cardback.jpg"))); // NOI18N
        btnCard4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard4ActionPerformed(evt);
            }
        });

        btnCard6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchinggameswaine/cardback.jpg"))); // NOI18N
        btnCard6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard6ActionPerformed(evt);
            }
        });

        btnCard5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchinggameswaine/cardback.jpg"))); // NOI18N
        btnCard5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard5ActionPerformed(evt);
            }
        });

        btnCard8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchinggameswaine/cardback.jpg"))); // NOI18N
        btnCard8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard8ActionPerformed(evt);
            }
        });

        btnCard7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchinggameswaine/cardback.jpg"))); // NOI18N
        btnCard7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard7ActionPerformed(evt);
            }
        });

        btnCard10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchinggameswaine/cardback.jpg"))); // NOI18N
        btnCard10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard10ActionPerformed(evt);
            }
        });

        btnCard9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchinggameswaine/cardback.jpg"))); // NOI18N
        btnCard9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard9ActionPerformed(evt);
            }
        });

        btnCard12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchinggameswaine/cardback.jpg"))); // NOI18N
        btnCard12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard12ActionPerformed(evt);
            }
        });

        btnCard11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchinggameswaine/cardback.jpg"))); // NOI18N
        btnCard11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard11ActionPerformed(evt);
            }
        });

        btnCard14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchinggameswaine/cardback.jpg"))); // NOI18N
        btnCard14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard14ActionPerformed(evt);
            }
        });

        btnCard13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchinggameswaine/cardback.jpg"))); // NOI18N
        btnCard13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard13ActionPerformed(evt);
            }
        });

        btnCard16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchinggameswaine/cardback.jpg"))); // NOI18N
        btnCard16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard16ActionPerformed(evt);
            }
        });

        btnCard15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchinggameswaine/cardback.jpg"))); // NOI18N
        btnCard15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard15ActionPerformed(evt);
            }
        });

        btnPlay.setText("Play");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        btnGuessAgain.setText("Guess Again");
        btnGuessAgain.setActionCommand("");
        btnGuessAgain.setAutoscrolls(true);
        btnGuessAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuessAgainActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.setActionCommand("");
        btnExit.setAutoscrolls(true);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(btnPlay)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGuessAgain))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnCard2)
                                    .addComponent(btnCard1)
                                    .addComponent(btnCard4)
                                    .addComponent(btnCard3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnCard6)
                                    .addComponent(btnCard5)
                                    .addComponent(btnCard8)
                                    .addComponent(btnCard7))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnCard10)
                                    .addComponent(btnCard9)
                                    .addComponent(btnCard12)
                                    .addComponent(btnCard11))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnCard14)
                                    .addComponent(btnCard13)
                                    .addComponent(btnCard16)
                                    .addComponent(btnCard15)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnExit)
                                .addGap(11, 11, 11)))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCard1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCard2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCard3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCard4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCard13, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCard14, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCard15, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCard16, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCard5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCard6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCard7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCard8, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCard9, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCard10, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCard11, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCard12, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPlay)
                    .addComponent(btnGuessAgain)
                    .addComponent(btnExit))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);//Trust the OS to release resources when the process exits
    }//GEN-LAST:event_btnExitActionPerformed

    //Hit play button
    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        //Reset all cards to default state
        for (int z=0; z <= 15; z++)
        {
            change[z] = 1;
        }
        
        //Add every card type to arraylist twice
        String temp;
        for (int x=0; x <= 7; x++)
        {
            for (int y = 1; y <= 2; y++)
            {
                temp = Integer.toString(x);
                set.add(temp);
            }
        }
        
        //Randomly assign card types from set to cards
        for (int x = 0; x <= 15; x++)
        {
            double index = Math.floor(Math.random() *(16-x));//Randomly choose index in card set
            int index1 = (int) index;//cast to int
            cards.add(set.get(index1));//set card
            set.remove(set.get(index1));//remove from avaliable cards
        }
        
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnCard1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard1ActionPerformed
        
        String temp = cards.get(0);//Get value of card
        
        if (temp.equals("0"))//Check what card we are and change to that
        {
            btnCard1.setIcon(a);
        }
        else if (temp.equals("1"))
        {
            btnCard1.setIcon(b);
        }
        else if (temp.equals("2"))
        {
            btnCard1.setIcon(c);
        }
        else if (temp.equals("3"))
        {
            btnCard1.setIcon(d);
        }
        else if (temp.equals("4"))
        {
            btnCard1.setIcon(e);
        }
        else if (temp.equals("5"))
        {
            btnCard1.setIcon(f);
        }
        else if (temp.equals("6"))
        {
            btnCard1.setIcon(g);
        }
        else if (temp.equals("7"))
        {
            btnCard1.setIcon(h);
        }
        
        count++;
        if (count == 1)
        {
            c1 = Integer.parseInt(temp);
            change[0] = 0;
        }
        else if (count==2)
        {
            c2 = Integer.parseInt(temp);
            change[0] = 0;
        }
        
    }//GEN-LAST:event_btnCard1ActionPerformed

    private void btnGuessAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuessAgainActionPerformed
        
        count = 0;
        if (c1 == c2)
        {
            for (int y = 1; y <= 2; y++)
            {
                if (change[0] == 0)
                {
                    btnCard1.setIcon(done);
                    change[0] = 2;
                } 
                else if (change[1] == 0) 
                {
                    btnCard2.setIcon(done);
                    change[1] = 2;
                } 
                else if (change[2] == 0) 
                {
                    btnCard3.setIcon(done);
                    change[2] = 2;
                }
                else if (change[3] == 0) 
                {
                    btnCard4.setIcon(done);
                    change[3] = 2;
                }
                else if (change[4] == 0) 
                {
                    btnCard5.setIcon(done);
                    change[4] = 2;
                }
                else if (change[5] == 0) 
                {
                    btnCard6.setIcon(done);
                    change[5] = 2;
                }
                else if (change[6] == 0) 
                {
                    btnCard7.setIcon(done);
                    change[6] = 2;
                }
                else if (change[7] == 0) 
                {
                    btnCard8.setIcon(done);
                    change[7] = 2;
                }
                else if (change[8] == 0) 
                {
                    btnCard9.setIcon(done);
                    change[8] = 2;
                }
                else if (change[9] == 0) 
                {
                    btnCard10.setIcon(done);
                    change[9] = 2;
                }
                else if (change[10] == 0) 
                {
                    btnCard11.setIcon(done);
                    change[10] = 2;
                }
                else if (change[11] == 0) 
                {
                    btnCard12.setIcon(done);
                    change[11] = 2;
                }
                else if (change[12] == 0) 
                {
                    btnCard13.setIcon(done);
                    change[12] = 2;
                }
                else if (change[13] == 0) 
                {
                    btnCard14.setIcon(done);
                    change[13] = 2;
                }
                else if (change[14] == 0) 
                {
                    btnCard15.setIcon(done);
                    change[14] = 2;
                }
                else if (change[15] == 0) 
                {
                    btnCard16.setIcon(done);
                    change[15] = 2;
                }
            }
        } 
        else 
        {
            for (int y = 1; y<=2; y++) 
            {
                if (change[0] == 0) 
                {
                    btnCard1.setIcon(back);
                    change[0] = 1;
                } 
                else if (change[1] == 0) 
                {
                    btnCard2.setIcon(back);
                    change[1] = 1;
                }
                else if (change[2] == 0) 
                {
                    btnCard3.setIcon(back);
                    change[2] = 1;
                }
                else if (change[3] == 0) 
                {
                    btnCard4.setIcon(back);
                    change[3] = 1;
                }
                else if (change[4] == 0) 
                {
                    btnCard5.setIcon(back);
                    change[4] = 1;
                }
                else if (change[5] == 0) 
                {
                    btnCard6.setIcon(back);
                    change[5] = 1;
                }
                else if (change[6] == 0) 
                {
                    btnCard7.setIcon(back);
                    change[6] = 1;
                }
                else if (change[7] == 0) 
                {
                    btnCard8.setIcon(back);
                    change[7] = 1;
                }
                else if (change[8] == 0) 
                {
                    btnCard9.setIcon(back);
                    change[8] = 1;
                }
                else if (change[9] == 0) 
                {
                    btnCard10.setIcon(back);
                    change[9] = 1;
                }
                else if (change[10] == 0) 
                {
                    btnCard11.setIcon(back);
                    change[10] = 1;
                }
                else if (change[11] == 0) 
                {
                    btnCard12.setIcon(back);
                    change[11] = 1;
                }
                else if (change[12] == 0) 
                {
                    btnCard13.setIcon(back);
                    change[12] = 1;
                }
                else if (change[13] == 0) 
                {
                    btnCard14.setIcon(back);
                    change[13] = 1;
                }
                else if (change[14] == 0) 
                {
                    btnCard15.setIcon(back);
                    change[14] = 1;
                }
                else if (change[15] == 0) 
                {
                    btnCard16.setIcon(back);
                    change[15] = 1;
                }
            } 
        }
        
    }//GEN-LAST:event_btnGuessAgainActionPerformed
    //These are all the same
    private void btnCard2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard2ActionPerformed
        
        String temp = cards.get(1);
        
        if (temp.equals("0"))
        {
            btnCard2.setIcon(a); // NOI18N
        }
        else if (temp.equals("1"))
        {
            btnCard2.setIcon(b);
        }
        else if (temp.equals("2"))
        {
            btnCard2.setIcon(c);
        }
        else if (temp.equals("3"))
        {
            btnCard2.setIcon(d);
        }
        else if (temp.equals("4"))
        {
            btnCard2.setIcon(e);
        }
        else if (temp.equals("5"))
        {
            btnCard2.setIcon(f);
        }
        else if (temp.equals("6"))
        {
            btnCard2.setIcon(g);
        }
        else if (temp.equals("7"))
        {
            btnCard2.setIcon(h);
        }
        
        count++;
        if (count == 1)
        {
            c1 = Integer.parseInt(temp);
            change[1] = 0;
        }
        else if (count==2)
        {
            c2 = Integer.parseInt(temp);
            change[1]=0;
        }
        
    }//GEN-LAST:event_btnCard2ActionPerformed

    private void btnCard3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard3ActionPerformed
        String temp = cards.get(2);
        
        if (temp.equals("0"))
        {
            btnCard3.setIcon(a); // NOI18N
        }
        else if (temp.equals("1"))
        {
            btnCard3.setIcon(b);
        }
        else if (temp.equals("2"))
        {
            btnCard3.setIcon(c);
        }
        else if (temp.equals("3"))
        {
            btnCard3.setIcon(d);
        }
        else if (temp.equals("4"))
        {
            btnCard3.setIcon(e);
        }
        else if (temp.equals("5"))
        {
            btnCard3.setIcon(f);
        }
        else if (temp.equals("6"))
        {
            btnCard3.setIcon(g);
        }
        else if (temp.equals("7"))
        {
            btnCard3.setIcon(h);
        }
        
        count++;
        if (count == 1)
        {
            c1 = Integer.parseInt(temp);
            change[2] = 0;
        }
        else if (count==2)
        {
            c2 = Integer.parseInt(temp);
            change[2]=0;
        }
    }//GEN-LAST:event_btnCard3ActionPerformed

    private void btnCard4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard4ActionPerformed
        String temp = cards.get(3);
        
        if (temp.equals("0"))
        {
            btnCard4.setIcon(a); // NOI18N
        }
        else if (temp.equals("1"))
        {
            btnCard4.setIcon(b);
        }
        else if (temp.equals("2"))
        {
            btnCard4.setIcon(c);
        }
        else if (temp.equals("3"))
        {
            btnCard4.setIcon(d);
        }
        else if (temp.equals("4"))
        {
            btnCard4.setIcon(e);
        }
        else if (temp.equals("5"))
        {
            btnCard4.setIcon(f);
        }
        else if (temp.equals("6"))
        {
            btnCard4.setIcon(g);
        }
        else if (temp.equals("7"))
        {
            btnCard4.setIcon(h);
        }
        
        count++;
        if (count == 1)
        {
            c1 = Integer.parseInt(temp);
            change[3] = 0;
        }
        else if (count==2)
        {
            c2 = Integer.parseInt(temp);
            change[3]=0;
        }
    }//GEN-LAST:event_btnCard4ActionPerformed

    private void btnCard5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard5ActionPerformed
        String temp = cards.get(4);
        
        if (temp.equals("0"))
        {
            btnCard5.setIcon(a); // NOI18N
        }
        else if (temp.equals("1"))
        {
            btnCard5.setIcon(b);
        }
        else if (temp.equals("2"))
        {
            btnCard5.setIcon(c);
        }
        else if (temp.equals("3"))
        {
            btnCard5.setIcon(d);
        }
        else if (temp.equals("4"))
        {
            btnCard5.setIcon(e);
        }
        else if (temp.equals("5"))
        {
            btnCard5.setIcon(f);
        }
        else if (temp.equals("6"))
        {
            btnCard5.setIcon(g);
        }
        else if (temp.equals("7"))
        {
            btnCard5.setIcon(h);
        }
        
        count++;
        if (count == 1)
        {
            c1 = Integer.parseInt(temp);
            change[4] = 0;
        }
        else if (count==2)
        {
            c2 = Integer.parseInt(temp);
            change[4]=0;
        }
    }//GEN-LAST:event_btnCard5ActionPerformed

    private void btnCard6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard6ActionPerformed
        String temp = cards.get(5);
        
        if (temp.equals("0"))
        {
            btnCard6.setIcon(a); // NOI18N
        }
        else if (temp.equals("1"))
        {
            btnCard6.setIcon(b);
        }
        else if (temp.equals("2"))
        {
            btnCard6.setIcon(c);
        }
        else if (temp.equals("3"))
        {
            btnCard6.setIcon(d);
        }
        else if (temp.equals("4"))
        {
            btnCard6.setIcon(e);
        }
        else if (temp.equals("5"))
        {
            btnCard6.setIcon(f);
        }
        else if (temp.equals("6"))
        {
            btnCard6.setIcon(g);
        }
        else if (temp.equals("7"))
        {
            btnCard6.setIcon(h);
        }
        
        count++;
        if (count == 1)
        {
            c1 = Integer.parseInt(temp);
            change[5] = 0;
        }
        else if (count==2)
        {
            c2 = Integer.parseInt(temp);
            change[5]=0;
        }
    }//GEN-LAST:event_btnCard6ActionPerformed

    private void btnCard7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard7ActionPerformed
        String temp = cards.get(6);
        
        if (temp.equals("0"))
        {
            btnCard7.setIcon(a); // NOI18N
        }
        else if (temp.equals("1"))
        {
            btnCard7.setIcon(b);
        }
        else if (temp.equals("2"))
        {
            btnCard7.setIcon(c);
        }
        else if (temp.equals("3"))
        {
            btnCard7.setIcon(d);
        }
        else if (temp.equals("4"))
        {
            btnCard7.setIcon(e);
        }
        else if (temp.equals("5"))
        {
            btnCard7.setIcon(f);
        }
        else if (temp.equals("6"))
        {
            btnCard7.setIcon(g);
        }
        else if (temp.equals("7"))
        {
            btnCard7.setIcon(h);
        }
        
        count++;
        if (count == 1)
        {
            c1 = Integer.parseInt(temp);
            change[6] = 0;
        }
        else if (count==2)
        {
            c2 = Integer.parseInt(temp);
            change[6]=0;
        }
    }//GEN-LAST:event_btnCard7ActionPerformed

    private void btnCard8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard8ActionPerformed
        String temp = cards.get(7);
        
        if (temp.equals("0"))
        {
            btnCard8.setIcon(a); // NOI18N
        }
        else if (temp.equals("1"))
        {
            btnCard8.setIcon(b);
        }
        else if (temp.equals("2"))
        {
            btnCard8.setIcon(c);
        }
        else if (temp.equals("3"))
        {
            btnCard8.setIcon(d);
        }
        else if (temp.equals("4"))
        {
            btnCard8.setIcon(e);
        }
        else if (temp.equals("5"))
        {
            btnCard8.setIcon(f);
        }
        else if (temp.equals("6"))
        {
            btnCard8.setIcon(g);
        }
        else if (temp.equals("7"))
        {
            btnCard8.setIcon(h);
        }
        
        count++;
        if (count == 1)
        {
            c1 = Integer.parseInt(temp);
            change[7] = 0;
        }
        else if (count==2)
        {
            c2 = Integer.parseInt(temp);
            change[7]=0;
        }
    }//GEN-LAST:event_btnCard8ActionPerformed

    private void btnCard9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard9ActionPerformed
        String temp = cards.get(8);
        
        if (temp.equals("0"))
        {
            btnCard9.setIcon(a); // NOI18N
        }
        else if (temp.equals("1"))
        {
            btnCard9.setIcon(b);
        }
        else if (temp.equals("2"))
        {
            btnCard9.setIcon(c);
        }
        else if (temp.equals("3"))
        {
            btnCard9.setIcon(d);
        }
        else if (temp.equals("4"))
        {
            btnCard9.setIcon(e);
        }
        else if (temp.equals("5"))
        {
            btnCard9.setIcon(f);
        }
        else if (temp.equals("6"))
        {
            btnCard9.setIcon(g);
        }
        else if (temp.equals("7"))
        {
            btnCard9.setIcon(h);
        }
        
        count++;
        if (count == 1)
        {
            c1 = Integer.parseInt(temp);
            change[8] = 0;
        }
        else if (count==2)
        {
            c2 = Integer.parseInt(temp);
            change[8]=0;
        }
    }//GEN-LAST:event_btnCard9ActionPerformed

    private void btnCard10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard10ActionPerformed
        String temp = cards.get(9);
        
        if (temp.equals("0"))
        {
            btnCard10.setIcon(a); // NOI18N
        }
        else if (temp.equals("1"))
        {
            btnCard10.setIcon(b);
        }
        else if (temp.equals("2"))
        {
            btnCard10.setIcon(c);
        }
        else if (temp.equals("3"))
        {
            btnCard10.setIcon(d);
        }
        else if (temp.equals("4"))
        {
            btnCard10.setIcon(e);
        }
        else if (temp.equals("5"))
        {
            btnCard10.setIcon(f);
        }
        else if (temp.equals("6"))
        {
            btnCard10.setIcon(g);
        }
        else if (temp.equals("7"))
        {
            btnCard10.setIcon(h);
        }
        
        count++;
        if (count == 1)
        {
            c1 = Integer.parseInt(temp);
            change[9] = 0;
        }
        else if (count==2)
        {
            c2 = Integer.parseInt(temp);
            change[9]=0;
        }
    }//GEN-LAST:event_btnCard10ActionPerformed

    private void btnCard11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard11ActionPerformed
        String temp = cards.get(10);
        
        if (temp.equals("0"))
        {
            btnCard11.setIcon(a); // NOI18N
        }
        else if (temp.equals("1"))
        {
            btnCard11.setIcon(b);
        }
        else if (temp.equals("2"))
        {
            btnCard11.setIcon(c);
        }
        else if (temp.equals("3"))
        {
            btnCard11.setIcon(d);
        }
        else if (temp.equals("4"))
        {
            btnCard11.setIcon(e);
        }
        else if (temp.equals("5"))
        {
            btnCard11.setIcon(f);
        }
        else if (temp.equals("6"))
        {
            btnCard11.setIcon(g);
        }
        else if (temp.equals("7"))
        {
            btnCard11.setIcon(h);
        }
        
        count++;
        if (count == 1)
        {
            c1 = Integer.parseInt(temp);
            change[10] = 0;
        }
        else if (count==2)
        {
            c2 = Integer.parseInt(temp);
            change[10]=0;
        }
    }//GEN-LAST:event_btnCard11ActionPerformed

    private void btnCard12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard12ActionPerformed
        String temp = cards.get(11);
        
        if (temp.equals("0"))
        {
            btnCard12.setIcon(a); // NOI18N
        }
        else if (temp.equals("1"))
        {
            btnCard12.setIcon(b);
        }
        else if (temp.equals("2"))
        {
            btnCard12.setIcon(c);
        }
        else if (temp.equals("3"))
        {
            btnCard12.setIcon(d);
        }
        else if (temp.equals("4"))
        {
            btnCard12.setIcon(e);
        }
        else if (temp.equals("5"))
        {
            btnCard12.setIcon(f);
        }
        else if (temp.equals("6"))
        {
            btnCard12.setIcon(g);
        }
        else if (temp.equals("7"))
        {
            btnCard12.setIcon(h);
        }
        
        count++;
        if (count == 1)
        {
            c1 = Integer.parseInt(temp);
            change[11] = 0;
        }
        else if (count==2)
        {
            c2 = Integer.parseInt(temp);
            change[11]=0;
        }
    }//GEN-LAST:event_btnCard12ActionPerformed

    private void btnCard13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard13ActionPerformed
        String temp = cards.get(12);
        
        if (temp.equals("0"))
        {
            btnCard13.setIcon(a); // NOI18N
        }
        else if (temp.equals("1"))
        {
            btnCard13.setIcon(b);
        }
        else if (temp.equals("2"))
        {
            btnCard13.setIcon(c);
        }
        else if (temp.equals("3"))
        {
            btnCard13.setIcon(d);
        }
        else if (temp.equals("4"))
        {
            btnCard13.setIcon(e);
        }
        else if (temp.equals("5"))
        {
            btnCard13.setIcon(f);
        }
        else if (temp.equals("6"))
        {
            btnCard13.setIcon(g);
        }
        else if (temp.equals("7"))
        {
            btnCard13.setIcon(h);
        }
        
        count++;
        if (count == 1)
        {
            c1 = Integer.parseInt(temp);
            change[12] = 0;
        }
        else if (count==2)
        {
            c2 = Integer.parseInt(temp);
            change[12]=0;
        }
    }//GEN-LAST:event_btnCard13ActionPerformed

    private void btnCard14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard14ActionPerformed
        String temp = cards.get(13);
        
        if (temp.equals("0"))
        {
            btnCard14.setIcon(a); // NOI18N
        }
        else if (temp.equals("1"))
        {
            btnCard14.setIcon(b);
        }
        else if (temp.equals("2"))
        {
            btnCard14.setIcon(c);
        }
        else if (temp.equals("3"))
        {
            btnCard14.setIcon(d);
        }
        else if (temp.equals("4"))
        {
            btnCard14.setIcon(e);
        }
        else if (temp.equals("5"))
        {
            btnCard14.setIcon(f);
        }
        else if (temp.equals("6"))
        {
            btnCard14.setIcon(g);
        }
        else if (temp.equals("7"))
        {
            btnCard14.setIcon(h);
        }
        
        count++;
        if (count == 1)
        {
            c1 = Integer.parseInt(temp);
            change[13] = 0;
        }
        else if (count==2)
        {
            c2 = Integer.parseInt(temp);
            change[13]=0;
        }
    }//GEN-LAST:event_btnCard14ActionPerformed

    private void btnCard15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard15ActionPerformed
        String temp = cards.get(14);
        
        if (temp.equals("0"))
        {
            btnCard15.setIcon(a); // NOI18N
        }
        else if (temp.equals("1"))
        {
            btnCard15.setIcon(b);
        }
        else if (temp.equals("2"))
        {
            btnCard15.setIcon(c);
        }
        else if (temp.equals("3"))
        {
            btnCard15.setIcon(d);
        }
        else if (temp.equals("4"))
        {
            btnCard15.setIcon(e);
        }
        else if (temp.equals("5"))
        {
            btnCard15.setIcon(f);
        }
        else if (temp.equals("6"))
        {
            btnCard15.setIcon(g);
        }
        else if (temp.equals("7"))
        {
            btnCard15.setIcon(h);
        }
        
        count++;
        if (count == 1)
        {
            c1 = Integer.parseInt(temp);
            change[14] = 0;
        }
        else if (count==2)
        {
            c2 = Integer.parseInt(temp);
            change[14]=0;
        }
    }//GEN-LAST:event_btnCard15ActionPerformed

    private void btnCard16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard16ActionPerformed
        String temp = cards.get(15);
        
        if (temp.equals("0"))
        {
            btnCard16.setIcon(a); // NOI18N
        }
        else if (temp.equals("1"))
        {
            btnCard16.setIcon(b);
        }
        else if (temp.equals("2"))
        {
            btnCard16.setIcon(c);
        }
        else if (temp.equals("3"))
        {
            btnCard16.setIcon(d);
        }
        else if (temp.equals("4"))
        {
            btnCard16.setIcon(e);
        }
        else if (temp.equals("5"))
        {
            btnCard16.setIcon(f);
        }
        else if (temp.equals("6"))
        {
            btnCard16.setIcon(g);
        }
        else if (temp.equals("7"))
        {
            btnCard16.setIcon(h);
        }
        
        count++;
        if (count == 1)
        {
            c1 = Integer.parseInt(temp);
            change[15] = 0;
        }
        else if (count==2)
        {
            c2 = Integer.parseInt(temp);
            change[15]=0;
        }
    }//GEN-LAST:event_btnCard16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(matchingGameSwaineUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(matchingGameSwaineUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(matchingGameSwaineUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(matchingGameSwaineUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new matchingGameSwaineUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCard1;
    private javax.swing.JButton btnCard10;
    private javax.swing.JButton btnCard11;
    private javax.swing.JButton btnCard12;
    private javax.swing.JButton btnCard13;
    private javax.swing.JButton btnCard14;
    private javax.swing.JButton btnCard15;
    private javax.swing.JButton btnCard16;
    private javax.swing.JButton btnCard2;
    private javax.swing.JButton btnCard3;
    private javax.swing.JButton btnCard4;
    private javax.swing.JButton btnCard5;
    private javax.swing.JButton btnCard6;
    private javax.swing.JButton btnCard7;
    private javax.swing.JButton btnCard8;
    private javax.swing.JButton btnCard9;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGuessAgain;
    private javax.swing.JButton btnPlay;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
